# Generated by Django 4.2.6 on 2023-11-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('blood_group', models.CharField(max_length=5)),
                ('dob', models.DateField()),
                ('sex', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('previous_donation', models.BooleanField(default=False)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabin_no', models.CharField(max_length=50, unique=True)),
                ('floor_no', models.CharField(max_length=50)),
                ('booked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('total_days', models.IntegerField()),
                ('total_bill', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('booked_date', models.DateField(auto_now_add=True)),
                ('cabin_type', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double')], max_length=50)),
            ],
            options={
                'db_table': 'cabins',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'supports',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_no', models.CharField(max_length=50)),
                ('floor_no', models.CharField(max_length=50)),
                ('booked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('total_days', models.IntegerField()),
                ('total_bill', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('booked_date', models.DateField(auto_now_add=True)),
                ('ward_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'wards',
            },
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='doctor',
        ),
        migrations.AddField(
            model_name='doctor',
            name='availability',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_name',
            field=models.CharField(default='Default Doctor Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterModelTable(
            name='prescription',
            table='prescription',
        ),
    ]
