# Generated by Django 4.2.6 on 2023-11-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0002_blooddonor_cabin_support_ward_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BloodDonor',
            new_name='BloodDonors',
        ),
        migrations.AlterModelTable(
            name='blooddonors',
            table='blooddonors',
        ),
    ]
