# Generated by Django 4.2.6 on 2023-11-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0003_rename_blooddonor_blooddonors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('doctor_email', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=20)),
                ('time_slot', models.CharField(max_length=20)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='BloodAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=5, unique=True)),
                ('total_bags', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'blood_availability',
            },
        ),
        migrations.CreateModel(
            name='BloodRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('blood_group', models.CharField(max_length=5)),
                ('bags_needed', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'bloodrecipient',
            },
        ),
        migrations.CreateModel(
            name='TestBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=255)),
                ('doctor_email', models.EmailField(max_length=254)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_email', models.EmailField(max_length=254)),
                ('test_name', models.JSONField()),
                ('total_bill', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'test_bill',
            },
        ),
        migrations.CreateModel(
            name='TestCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'testcharge',
            },
        ),
        migrations.AlterModelTable(
            name='doctor',
            table='doctors',
        ),
    ]
