# Generated by Django 4.2.6 on 2023-11-29 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0004_appointment_bloodavailability_bloodrecipient_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment',
            table='appointment',
        ),
    ]
