# Generated by Django 4.2.6 on 2023-11-29 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0005_alter_appointment_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='appointment_datetime',
        ),
    ]
