# Generated by Django 4.2.6 on 2023-11-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0006_rename_date_appointment_appointment_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='time_slot',
        ),
    ]
